# Generated by Django 3.2.13 on 2022-06-13 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_rename_color_hexcode_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'пожалуйста введите валидный шестнадцатеричный цветовой код')], verbose_name='Цветовой HEX-код'),
        ),
    ]
