# Generated by Django 3.2.13 on 2022-06-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_editor',
        ),
    ]
